#ifndef EXECUTION_ORDER_H
#define EXECUTION_ORDER_H

#define EXECUTION_ORDER_IO_EVENTS   -1000
#define EXECUTION_ORDER_PRE_RENDER  1000
#define EXECUTION_ORDER_RENDER      2000
#define EXECUTION_ORDER_POST_RENDER 3000

#endif // EXECUTION_ORDER_H